"""
firebase_admin_setup.py

Initializes the Firebase Admin SDK using a service account JSON file and
provides accessor functions for Firebase Auth and Firestore clients. Used
by authentication-related endpoints that require Firebase services.

Author: Anna Yabut
"""

import os
import firebase_admin
from firebase_admin import credentials, auth, firestore
from dotenv import load_dotenv

load_dotenv()


def initialize_firebase_admin() -> firebase_admin.App:
    """
    Initializes the Firebase Admin SDK if it has not already been initialized.

    Reads the service account path from environment variables and creates a
    Firebase app instance. Ensures initialization only occurs once.

    Returns:
        The initialized Firebase app instance.

    Raises:
        ValueError: If the service account path is not set in environment variables.
    """
    if not firebase_admin._apps:
        service_account_path = os.getenv("FIREBASE_SERVICE_ACCOUNT_PATH")

        if not service_account_path:
            raise ValueError("FIREBASE_SERVICE_ACCOUNT_PATH is not set")

        # Initialize Firebase only once using the provided service account
        cred = credentials.Certificate(service_account_path)
        firebase_admin.initialize_app(cred)

    app = firebase_admin.get_app()
    return app


def get_firebase_auth():
    """
    Provides the Firebase Auth module after ensuring initialization.

    Returns:
        Firebase Admin Auth module used for authentication operations.
    """
    initialize_firebase_admin()
    return auth


def get_firestore_client() -> firestore.Client:
    """
    Provides a Firestore client instance after ensuring initialization.

    Returns:
        Firestore client for database operations.
    """
    initialize_firebase_admin()
    return firestore.client()


def generate_password_reset_link(email: str) -> str:
    """
    Generates a Firebase password reset link for a given user email.

    Args:
        email: User email address to generate the reset link for.

    Returns:
        A password reset URL generated by Firebase Auth.
    """
    initialize_firebase_admin()
    return auth.generate_password_reset_link(email)